-- 1. What are the details of all cars purchased in the year 2022?
select *
from sales
    join cars on sales.car_id = cars.car_id
where purchase_date like "2022%";



-- 2. What is the total number of cars sold by each salesperson?
select sales.salesman_id as "id", salespersons.name as "name", count(salespersons.salesman_id) as "total cars sold"
from sales
    join salespersons on sales.salesman_id = salespersons.salesman_id
group by salespersons.salesman_id;

/*
| id  | name       | total cars sold |
| --- | ---------- | --------------- |
| 1   | John Smith | 5               |
| 2   | Emily Wong | 5               |
| 3   | Tom Lee    | 6               |
| 4   | Lucy Chen  | 4               |
*/

-- 3. What is the total revenue generated by each salesperson?
select sales.salesman_id as "id", salespersons.name as "name", sum(cost_$) as "total revenue"
from sales
	join salespersons
	on sales.salesman_id = salespersons.salesman_id
    join cars
    on sales.car_id = cars.car_id
group by salespersons.salesman_id;

-- 4. What are the details of the cars sold by each salesperson?
select salespersons.name as "sold by",
	sales.purchase_date as "date of purchase",
    concat(make," ",type) as "car",
    style,
    cost_$
from sales
	join salespersons
	on sales.salesman_id = salespersons.salesman_id
    join cars
    on sales.car_id = cars.car_id
order by salespersons.salesman_id;

-- 5. What is the total revenue generated by each car type?
select cars.type,
    sum(cost_$) as "total revenue"
from sales
    join cars
    on sales.car_id = cars.car_id
group by cars.type;

-- 6. What are the details of the cars sold in the year 2021 by salesperson 'Emily Wong'?
select purchase_date, 
	make,
    type,
    style,
    cost_$
from sales
	join salespersons
	on sales.salesman_id = salespersons.salesman_id
    join cars
    on sales.car_id = cars.car_id
where purchase_date like "2021%"
	AND salespersons.name = "Emily Wong"

-- 7. What is the total revenue generated by the sales of hatchback cars?
-- 8. What is the total revenue generated by the sales of SUV cars in the year 2022?
-- 9. What is the name and city of the salesperson who sold the most number of cars in the year 2023?
--10. What is the name and age of the salesperson who generated the highest revenue in the year 2022?

